### ISSUE TITLE
Building doesn't work.

### ISSUE THREAD

**Issue by AeonCaptain** [seresharp/HollowKnight.Modding#36]
I might just be stupid, but I tried building this using the instructions, and can't figure out what I'm doing wrong. VSCommunity 2017 gives this error:
1>------ Build started: Project: PrePatcher, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.7.2" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(129,5): error MSB4018: The "GenerateRuntimeConfigurationFiles" task failed unexpectedly.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(129,5): error MSB4018: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\fang2\Documents\games\Hollow Knight (Gamepass)\PrePatcher\bin\Debug\net472\PrePatcher.runtimeconfig.json'.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(129,5): error MSB4018:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(129,5): error MSB4018:    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(129,5): error MSB4018:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(129,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateRuntimeConfigurationFiles.WriteToJsonFile(String fileName, Object value)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(129,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateRuntimeConfigurationFiles.WriteRuntimeConfig(ProjectContext projectContext)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(129,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateRuntimeConfigurationFiles.ExecuteCore()
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(129,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute()
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(129,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(129,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
1>Done building project "PrePatcher.csproj" -- FAILED.
2>------ Build started: Project: Assembly-CSharp, Configuration: Debug Any CPU ------
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Assembly-CSharp". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "PlayMaker". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "UnityEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "UnityEngine.AnimationModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "UnityEngine.AudioModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "UnityEngine.ImageConversionModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "UnityEngine.IMGUIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "UnityEngine.JSONSerializeModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "UnityEngine.ParticleSystemModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "UnityEngine.Physics2DModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "UnityEngine.TextRenderingModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "UnityEngine.UIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>Mod.cs(178,19,178,29): error CS1003: Syntax error, '(' expected
2>Mod.cs(178,77,178,78): error CS1026: ) expected
2>Mod.cs(180,19,180,22): error CS1003: Syntax error, '(' expected
2>Mod.cs(180,60,180,61): error CS1026: ) expected
2>Mod.cs(254,19,254,29): error CS1003: Syntax error, '(' expected
2>Mod.cs(254,75,254,76): error CS1026: ) expected
2>Mod.cs(256,19,256,22): error CS1003: Syntax error, '(' expected
2>Mod.cs(256,60,256,61): error CS1026: ) expected
2>ModGeneric.cs(45,32,45,33): error CS1525: Invalid expression term '='
2>ModGeneric.cs(176,38,176,39): error CS1525: Invalid expression term '='
2>ModGeneric.cs(197,19,197,29): error CS1003: Syntax error, '(' expected
2>ModGeneric.cs(197,79,197,80): error CS1026: ) expected
2>ModGeneric.cs(199,19,199,22): error CS1003: Syntax error, '(' expected
2>ModGeneric.cs(199,60,199,61): error CS1026: ) expected
2>ModGeneric.cs(221,19,221,29): error CS1003: Syntax error, '(' expected
2>ModGeneric.cs(221,81,221,82): error CS1026: ) expected
2>ModGeneric.cs(222,19,222,22): error CS1003: Syntax error, '(' expected
2>ModGeneric.cs(222,60,222,61): error CS1026: ) expected
2>ModHooks.cs(617,19,617,29): error CS1003: Syntax error, '(' expected
2>ModHooks.cs(617,68,617,69): error CS1026: ) expected
2>ModHooks.cs(619,19,619,31): error CS1003: Syntax error, '(' expected
2>ModHooks.cs(619,69,619,70): error CS1026: ) expected
2>Done building project "Assembly-CSharp.csproj" -- FAILED.
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========

**Comment by seresharp** [comment]
Looks like you're missing .net 4.7.2 (used by the prepatcher), as well as the vanilla game files.

**Comment by AeonCaptain** [comment]
![image](https://user-images.githubusercontent.com/56273352/102401792-16d0cf80-3fa1-11eb-9873-c2232c5b2adb.png)
![image](https://user-images.githubusercontent.com/56273352/102401836-23edbe80-3fa1-11eb-82a1-d933683294ac.png)
Are the files in the above images in the correct places? By installing .net 4.7.2, one of the things succeeded.
Build output:

1>------ Build started: Project: PrePatcher, Configuration: Debug Any CPU ------
1>PrePatcher -> C:\Users\fang2\Documents\games\Hollow Knight\PrePatcher\bin\Debug\net472\PrePatcher.exe
2>------ Build started: Project: Assembly-CSharp, Configuration: Debug Any CPU ------
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Assembly-CSharp". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "PlayMaker". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "UnityEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "UnityEngine.AnimationModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "UnityEngine.AudioModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "UnityEngine.ImageConversionModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "UnityEngine.IMGUIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "UnityEngine.JSONSerializeModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "UnityEngine.ParticleSystemModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "UnityEngine.Physics2DModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "UnityEngine.TextRenderingModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "UnityEngine.UIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>Mod.cs(178,19,178,29): error CS1003: Syntax error, '(' expected
2>Mod.cs(178,77,178,78): error CS1026: ) expected
2>ModHooks.cs(617,19,617,29): error CS1003: Syntax error, '(' expected
2>Mod.cs(180,19,180,22): error CS1003: Syntax error, '(' expected
2>ModHooks.cs(617,68,617,69): error CS1026: ) expected
2>ModHooks.cs(619,19,619,31): error CS1003: Syntax error, '(' expected
2>ModHooks.cs(619,69,619,70): error CS1026: ) expected
2>Mod.cs(180,60,180,61): error CS1026: ) expected
2>Mod.cs(254,19,254,29): error CS1003: Syntax error, '(' expected
2>Mod.cs(254,75,254,76): error CS1026: ) expected
2>Mod.cs(256,19,256,22): error CS1003: Syntax error, '(' expected
2>Mod.cs(256,60,256,61): error CS1026: ) expected
2>ModGeneric.cs(45,32,45,33): error CS1525: Invalid expression term '='
2>ModGeneric.cs(176,38,176,39): error CS1525: Invalid expression term '='
2>ModGeneric.cs(197,19,197,29): error CS1003: Syntax error, '(' expected
2>ModGeneric.cs(197,79,197,80): error CS1026: ) expected
2>ModGeneric.cs(199,19,199,22): error CS1003: Syntax error, '(' expected
2>ModGeneric.cs(199,60,199,61): error CS1026: ) expected
2>ModGeneric.cs(221,19,221,29): error CS1003: Syntax error, '(' expected
2>ModGeneric.cs(221,81,221,82): error CS1026: ) expected
2>ModGeneric.cs(222,19,222,22): error CS1003: Syntax error, '(' expected
2>ModGeneric.cs(222,60,222,61): error CS1026: ) expected
2>Done building project "Assembly-CSharp.csproj" -- FAILED.
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by fifty-six** [comment]
No. The vanilla folder is supposed to *be* a vanilla managed folder, not contain it.

**Comment by AeonCaptain** [comment]
![image](https://user-images.githubusercontent.com/56273352/102446069-2cb6b280-3fea-11eb-9706-191af26b64fc.png)
Fixed it (I think), if this is how the directory should look like.
It still gives this error though:

1>------ Build started: Project: Assembly-CSharp, Configuration: Debug Any CPU ------
1>Mod.cs(178,19,178,29): error CS1003: Syntax error, '(' expected
1>Mod.cs(178,77,178,78): error CS1026: ) expected
1>Mod.cs(180,19,180,22): error CS1003: Syntax error, '(' expected
1>Mod.cs(180,60,180,61): error CS1026: ) expected
1>Mod.cs(254,19,254,29): error CS1003: Syntax error, '(' expected
1>Mod.cs(254,75,254,76): error CS1026: ) expected
1>Mod.cs(256,19,256,22): error CS1003: Syntax error, '(' expected
1>Mod.cs(256,60,256,61): error CS1026: ) expected
1>ModGeneric.cs(45,32,45,33): error CS1525: Invalid expression term '='
1>ModGeneric.cs(176,38,176,39): error CS1525: Invalid expression term '='
1>ModGeneric.cs(197,19,197,29): error CS1003: Syntax error, '(' expected
1>ModGeneric.cs(197,79,197,80): error CS1026: ) expected
1>ModGeneric.cs(199,19,199,22): error CS1003: Syntax error, '(' expected
1>ModGeneric.cs(199,60,199,61): error CS1026: ) expected
1>ModGeneric.cs(221,19,221,29): error CS1003: Syntax error, '(' expected
1>ModGeneric.cs(221,81,221,82): error CS1026: ) expected
1>ModGeneric.cs(222,19,222,22): error CS1003: Syntax error, '(' expected
1>ModGeneric.cs(222,60,222,61): error CS1026: ) expected
1>ModHooks.cs(617,19,617,29): error CS1003: Syntax error, '(' expected
1>ModHooks.cs(617,68,617,69): error CS1026: ) expected
1>ModHooks.cs(619,19,619,31): error CS1003: Syntax error, '(' expected
1>ModHooks.cs(619,69,619,70): error CS1026: ) expected
1>Done building project "Assembly-CSharp.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

I think I'm just stupid and haven't figured out something obvious yet...

**Comment by AeonCaptain** [comment]
I don't know what I did, but it worked this time. I'm absolutely befuddled, but it worked anyway. Thank you for your help.
